### ISSUE TITLE
java.sql.SQLException: Access denied for user 'mqcloud'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by skymysky** [sohutv/mqcloud#6]
直接下载了MQCloud RELEASE 1.9.1的war包.
启动java -Dspring.profiles.active=online -Dfile.encoding=UTF-8 -DPROJECT_DIR=/opt/mqcloud-master/logs -jar mq-cloud.war
mysql的脚本执行过.检查没什么问题.  一直提示如下的报错信息.

2019-11-24 10:15:31.468 {localhost-startStop-1} INFO  o.s.boot.web.servlet.FilterRegistrationBean-258 - Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-11-24 10:15:31.469 {localhost-startStop-1} INFO  o.s.boot.web.servlet.FilterRegistrationBean-258 - Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-11-24 10:15:31.469 {localhost-startStop-1} INFO  o.s.boot.web.servlet.FilterRegistrationBean-258 - Mapping filter: 'requestContextFilter' to: [/*]
2019-11-24 10:15:31.469 {localhost-startStop-1} INFO  o.s.boot.web.servlet.FilterRegistrationBean-258 - Mapping filter: 'webRequestLoggingFilter' to: [/*]
2019-11-24 10:15:31.469 {localhost-startStop-1} INFO  o.s.boot.web.servlet.FilterRegistrationBean-258 - Mapping filter: 'applicationContextIdFilter' to: [/*]
2019-11-24 10:15:32.451 {main} ERROR org.apache.tomcat.jdbc.pool.ConnectionPool-182 - Unable to create initial connections of pool.
java.sql.SQLException: Access denied for user 'mqcloud'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.46.jar!/:5.1.46]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_211]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_211]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_211]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_211]

**Comment by gaoyf** [comment]
试下`mysql -h localhost -u mqcloud -p`这样能链接不？
如果不行，试下下面的命令：
```
create user 'mqcloud' identified by 'mqcloud';
grant all on *.* to 'mqcloud'@'%' identified by 'mqcloud' with grant option;   
flush privileges;
```

**Comment by skymysky** [comment]
[root@hz-zouqh-test-199-136-143 logs]# mysql -h localhost -u mqcloud -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'mqcloud'@'localhost' (using password: YES)

用户已经创建过了.
![image](https://user-images.githubusercontent.com/8543010/69510728-035b5c80-0f79-11ea-9b13-9324f6b1f921.png)

**Comment by skymysky** [comment]
mysql版本5.6.46  ,版本有什么要求吗?

**Comment by skymysky** [comment]
grant all privileges on *.* to mqcloud@localhost identified by 'mqcloud';     解决了. 因为mysql我用的本地.
